---
title: "Fünfter Vorlesungstermin (RStudio)"
author: "Dennis Klinkhammer (2022)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Aufgabe: MTCARS

### Analysemodell

```{r fig_1, echo=FALSE}
DiagrammeR::grViz("
digraph {
  graph [layout = circo]
  node [shape = circle]
    A [label = 'mpg']
    B [label = 'cyl']
    C [label = 'disp']
    D [label = 'hp']
    E [label = 'drat']
    F [label = 'wt']
    G [label = 'qsec']
    H [label = 'vs']
    I [label = 'am']
    J [label = 'gear']
    K [label = 'carb']
  edge []
    B -> F
    C -> F
    D -> F
    D -> G
    H -> D
    K -> D
    K -> F
    F -> A
    G -> A
    I -> A
    E -> F
    J -> F
}
")
```

### Univariate Analyse

````{r table_1, echo=TRUE}
summary(mtcars)
````

### Bivariate Analyse

````{r fig_2, echo=TRUE}
library(corrplot)
corrmatrix <- cor(mtcars)
corrplot.mixed(corrmatrix)
````

### Multivariate Analyse

````{r table_2, echo=TRUE}
summary(step(lm(mpg~., data=mtcars)))
````